#!/bin/bash

# base 이미지 설정
FROM openjdk:17-jre-alpine

# jar 파일 위치를 변수로 설정
ARG JAR_FILE=build\libs\hello-world-0.0.1-SNAPSHOT.jar

# 환경변수 설정
ENV CUSTOM_NAME helloWorld

ADD ${JAR_FILE} hello-world-0.0.1-SNAPSHOT.jar

# 외부 호스트 8080 포트로 노출
EXPOSE 8080

# 실행 명령어
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/hello-world-0.0.1-SNAPSHOT.jar"]